// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus_Server.Models;

public partial class Language
{
    [Key]
    public int LanguageId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Name { get; set; }

    // 導覽屬性
    public virtual ICollection<GameLanguage> GameLanguages { get; set; } = new List<GameLanguage>();
}