// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class ProductInformation
{
    [Key]
    public int ProductInformationId { get; set; }

    [Required]
    public int ComponentClassificationId { get; set; }
    public virtual ComponentClassification ComponentClassification { get; set; }

    [Required]
    [MaxLength(200)]
    public string Name { get; set; }
    
    #nullable enable

    [MaxLength(300)]
    public string? Specification { get; set; }

    [Required]
    public int Price { get; set; } = 0;

    [Required]
    public int Wattage { get; set; } = 0;

    public int? Recommend { get; set; } = 0;

    // 時間戳記 ~ 資料異動前當下版本的概念
    // 樂觀併發控制
    [Timestamp]
    public byte[]? Version { get; set; }

    public virtual ICollection<ProductCPU> ProductCPUs { get; set; } = new List<ProductCPU>();

    public virtual ICollection<ProductGPU> ProductGPUs { get; set; } = new List<ProductGPU>();

    public virtual ICollection<ProductRAM> ProductRAMs { get; set; } = new List<ProductRAM>();
}