// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus.Models;

public partial class ProductRAM
{
    [Key]
    public int ProductRAMId { get; set; }

    [Required]
    public int ProductInformationId { get; set; }

    [Required]
    public int Size { get; set; }

    public virtual ProductInformation ProductInformation { get; set; }
}