// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SteamNexus_Server.Models;

public partial class ProductCPU
{
    [Key]
    public int ProductCPUId { get; set; }

    [Required]
    public int ProductInformationId { get; set; }

    [Required]
    public int CPUId { get; set; }

    public virtual CPU CPU { get; set; }

    public virtual ProductInformation ProductInformation { get; set; }
}