// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SteamNexus.Models;

public partial class PlayersHistory
{
    [Key]
    public int PlayersHistoryId { get; set; }

    [Required]
    public int GameId { get; set; }

    [Required]
    public DateTime Date { get; set; } = DateTime.Now;

    [Required]
    public int Players { get; set; }

    public virtual Game Game { get; set; }
}