// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SteamNexus.Models;

public partial class TagGroup
{
    [Key]
    public int TagGroupId { get; set; }

    [Required]
    public int GameId { get; set; }

    [Required]
    public int TagId { get; set; }

    public virtual Game Game { get; set; }

    public virtual Tag Tag { get; set; }
}