// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamNexus.Models;

public partial class GameFollow
{
    public int GameFollowId { get; set; }

    public int MemberId { get; set; }

    public int GameId { get; set; }

    public DateTime? FollowTime { get; set; }

    public virtual Game Game { get; set; }

    public virtual User Member { get; set; }
}